blog/urls.py
from django.conf.urls import patterns, url
from blog import views

urlpatterns = patterns('',

                       url(r'^$', views.home_page, name='home_page'),
                       url(r'(?P<post_id>\d+)/', views.post, name='post'),
                       url(r'^publications/$', views.publications,
                           name='publications'),
                       url(r'^contacts/$', views.contacts, name='contacts'),
                       url(r"^search/", views.search, name='search'),)

myblog/urls.py
from django.conf.urls import patterns, include, url

from django.contrib import admin
admin.autodiscover()

urlpatterns = patterns('',
    url(r'^blog/', include('blog.urls', namespace='blog', app_name='blog')),

    url(r'^admin/', include(admin.site.urls)),
)

blog/models.py
from django.db import models


class Post(models.Model):
    title = models.CharField(max_length=100)
    body_text = models.TextField()
    author = models.CharField(max_length=100, default='Vankata')
    category = models.CharField(max_length=50, default='')
    pub_date = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.title


class Comments(models.Model):
    pub_date = models.DateTimeField(auto_now_add=True)
    author = models.CharField(max_length=60)
    body = models.TextField()
    post = models.ForeignKey(Post)
    email = models.EmailField()

blog/forms.py
from django.forms import ModelForm
from blog.models import Comments


class CommentForm(ModelForm):
    class Meta:
        model = Comments
        exclude = ["post"]

blog/views.py
from django.shortcuts import render, redirect
from blog.forms import CommentForm
from blog.models import Post, Comments
from django.db.models import Q


def home_page(request):
    posts = Post.objects.all().order_by("-pub_date")[:1]
    return render(request, "blog/index.html", {'posts': posts,
                                               'user': request.user})


def post(request, post_id):
    if request.method == "POST":
        p = request.POST
        author = "Anonymous"
        if p["author"]:
            author = p["author"]
        comment = Comments(post=Post.objects.get(pk=post_id))
        comment_form = CommentForm(request.POST, instance=comment)
        comment_form.fields["author"].required = False
        comment = comment_form.save(commit=False)
        comment.author = author
        comment.save()
        return redirect('blog/posts.html', args=(post_id,))
    post = Post.objects.get(pk=post_id)
    comments = Comments.objects.filter(post=post)
    context = {'post': post, 'user': request.user, 'comments': comments,
               'form': CommentForm()}
    return render(request, 'blog/posts.html', context)


def publications(request):
    posts = Post.objects.all().order_by('-pub_date')
    return render(request, 'blog/publications.html', {'posts': posts,
                                                      'user': request.user})


def contacts(request):
    return render(request, 'blog/contacts.html', {'user': request.user})


def search(request):
    searched_string = request.POST.get('searched_post', "")
    posts = Post.objects.filter(
        Q(title__icontains=searched_string) | Q(category__icontains=searched_string))\
        .order_by('-pub_date')
    return render(request, 'blog/results.html', {'posts': posts,
                                                 'user': request.user})

blog/templates/blog/base.html
{% load staticfiles %}


<!DOCTYPE html>
<html>
<head lang="en">
    <meta charset="UTF-8">
    <link rel="stylesheet" type="text/css" href="{% static 'blog/style.css' %}" />
    <title>{% block title%} My blog {% endblock %}</title>

</head>
<body>
<header><h1>My Blog</h1>

</header>
<div id="search">
    <form action="{% url 'blog:search' %}" method="post">{% csrf_token %}
    <input name="searched_post" type="text" placeholder="Enter title or category for search">
    <input type="submit" value="Search">
        </form>
</div>
    <div id="container">
        <div id="navigation">
            {% block nav-global %}
              <ul>
                <li><a href="{% url 'blog:home_page' %}">Home</a></li>
                <li><a href="{% url 'blog:publications' %}">All Posts</a></li>
                <li><a href="{% url 'blog:contacts' %}">Contacts</a></li>
                {% if user.is_staff %}
                <li><a href="{% url 'admin:index' %}">Admin panel</a></li>
                <li><a href="{% url 'admin:blog_post_add' %}">Add post</a></li>

                {% endif %}

                  </ul>
            {% endblock %}
        </div>

        <div id="content">
            {% block content %}{% endblock %}
        </div>
    </div>

</body>
</html>

blog/templates/blog/contacts.html
{% extends 'blog/base.html'%}

        {% block content%}
        <ul class="main contacts">
					<li>Main Editor: Ivan Vurbanov</li>
					<li>e-mail: vurbanoff@gmail.com</li>
                    <li><a href=" https://www.facebook.com/ivan.vurbanov">facebook</a></li>
            <li><a href="https://twitter.com/VurbanOFF">twitter </a></li>
            <li><a href='https://github.com/Vurbana'>github </a> </li>
            </ul>
        {% endblock%}

blog/templates/blog/index.html
{% extends "blog/base.html" %}


{% block content %}
    <div class="main">
       <ul>
        {% for post in posts %}
           <div class="one_post">
            <div class="title"><a href="{% url 'blog:post' post.id%}">{{ post.title }}</a></div>
            <ul>
                <div class="information">{{ post.pub_date }} | Author: {{post.author}}{% if post.category %} | Category:{{ post.category }} {% endif %}</div>
                <div class="body">{{ post.body_text|linebreaks }}</div>
                </ul>
               </div>
                <div id="view_comments">
                    <p><a href="{% url 'blog:post' post.id%}">View Comments({{post.comments_set.count}})</a></p></div>

        {% endfor %}
    </ul>
    </div>

{% endblock %}

blog/templates/blog/posts.html
{% extends 'blog/base.html'%}


    {% block content %}

<div class="title">{{ post.title }}</div>
<ul>
    <div class="information">{{ post.pub_date }}| Author: {{post.author}} {% if post.category %} | Category: {{ post.category }} {% endif %}</div>
    <div class="body">{{ post.body_text|linebreaks }}</div>
</ul>

{% if comments %}
    <p id="start_of_comments">Comments:</p>
{% endif %}

{% for comment in comments %}
    <div class="comment">
        <div class="information">{{ comment.pub_date }} | Author: {{ comment.author }}</div>
        <div class="comment_body">{{ comment.body|linebreaks }}</div>
    </div>
{% endfor %}

<div id="addc">Add a comment:</div>
<form action="{% url 'blog:post' post.id %}" method="POST">{% csrf_token %}
    <div id="cform">
        Name: {{ form.author }} <br />
        Email: {{form.email}}
        <p>{{ form.body|linebreaks }}</p>
    </div>
    <div id="submit"><input type="submit" value="Submit"></div>
</form>
        {% endblock %}

blog/templates/blog/publications.html
{% extends 'blog/base.html' %}

{% block content %}
    <div class="main">
       <ul>
        {% for post in posts %}
           <div class="one_post">
            <div class="title">
                <a href="{% url 'blog:post' post.id %}">{{ post.title }}</a>
            </div>
            <ul>
                <div class="information">{{ post.pub_date }} | Author: {{post.author}}{% if post.category %} | Category:{{ post.category }} {% endif %}</div>

            </ul>
               </div>
        {% endfor %}
    </ul>
    </div>

{% endblock %}

blog/templates/blog/results.html
{% extends 'blog/base.html'%}

        {% block title%} Search Results{% endblock%}
        {% block content%}
         <div class="main">
       <ul>
        {% for post in posts %}
           <div class="one_post">
            <div class="title">
                <a href="{% url 'blog:post' post.id %}">{{ post.title }}</a>
            </div>
            <ul>
                <div class="information">{{ post.pub_date }} | Author: {{post.author}}{% if post.category %} | Category:{{ post.category }} {% endif %}</div>

            </ul>
               </div>
        {% endfor %}
    </ul>
    </div>
        {% endblock%}